language: go

go:
  - '1.9'

services:
  - docker

env:
  global:
    - REPO=quay.io/wantedly/k8nskel
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e 's/[^a-zA-Z0-9]/_/g')
    - TAG=$BRANCH-${TRAVIS_COMMIT::8}
    - secure: "QrOs2ARkyVB9yY1e3GiUvb5xA6e10FCu2i7oIv01b0GkJkda8/CK/dLw6m7P8cJrVN+8Fci4N09WkcZsk+yzbG8k1A2R4b4AnYFN3qtTuEUmSuVoXZZk4m3A8ARDV2mQ5paPyp71usnlPkn/ZvGPG0YRVOap2o+Zjici7he2ixXrvT5jEo+dQy8VXS4rrYRlxLqqDBU5xm8kMZFA/14AhQ8An0/ty2itXPG1RpPeKlemaCFtsB8Zlj6qX30rgfTeBymhMDQqah5B8bg+XTM4yyfWDalExFbJZ7JlOfge56VEuf3q3lRgU5636CcCWS+ZNRQQlHd3c7JugCbKlEKqb0orifyitfSzmo9I3zWfO/eEwlVyJImqfpQV5zK3qZIFEy+JKMWD+739KzsAH1kRdXbJIlS+OSKnUC38GXu9oObVYUYKSY1yo8xrMjePqHMMKW3WAyudfdyRFs+PyBzbVlIjHZnYsRcWVLXjmACG3lArO4oxOPQpYP7Mig3vBxnQ7q5NRO3M5pBzXBC+GvCH+HdiK5OwFnQwasw2fUkSDqN8jeUJfYVlPLlI9ToInNtsYDDA8gyouth/9TwOfOWHQM0iJJGp2BAFdKRBFTyMwJndeFVUBxqdJCU4jXSx0XoOanIitYIvpK4WxG2m2wRYUJEtmyatYtsR1x44hRj6FR4="
    - secure: "Mm6WHCVHzIokxWwO2YvcY36j/nDSJ9KTx6DoM9dIqn6A6NfdhOmV37tV1gKDNg5dqjgZ+zjpPx2tM8Y/zrEV4Ml5Lu1Khvm/Pw5aJ19b2WIZGdSgD+OTNBXXpL9AlbWq5+IGs2n3nZJ3X+ALVYbfKtaMx7B7FA7fKXu1CAjUvT7WSV7z6j618L2P/BWnsUmPpGChGNXkp/b3iBga+kMK+nwV7xRAzxihys2uzPLVCcx7K5iIJCj0GZJZtKC2XTHg8y4QFbBuhHWSLSdlSFUaaKHSG0xTzUo/20w8HngdTTzTfVBqJGv8B9yzGW9UG+YE6+fDDyywnWJQ52k9mLB7qTxzLnL3DjxC5qTdqbIzIYJHFfuGkpAnQgzAp40DdZvQqX1EAWWRM1cySCGigXrZLjGhTw+b2UrA++1UWKPXZbGLt8qHKVKF8HzpJsTUySiGts21tFVg+x+SoHpINYmSdMufYSa4eNqM0u+Pd2YIEbVSN/F9MZHXYoNjDDDkifCKiqG3byobwTgPX0NbnFuxFKkGMlj5QYJthrXybzixGKbKTlQFQZ/38LSMmRHN9Ye+reG6v2WwWkMJru/3mT/rCwLtMxeKiLFCAKpDhOMwrjZrjnhNuRKNUIpNpsLuO4YqeNtYz5N0oK2SzF5ZMgB3zKw3dBnxaGILihT/RQieoiA="
    - secure: "kUwWuF+wh6BVGfH4K7z5/8q7gDRt+NxT5VvyN/olB8a5YsZpi3pVwHpdj7dR1GN/OtA/mMC3trS8QJx1PRkjr/nirmWYhBOi0spetAFM5Io/E0wxuGdDRtT+duWsGWYZj356HTPHLhW0BWSVy4mxkwxQySh3SZSNp3M+TfSkUd9AvC335VHFFhtL5MCQHam2IxMhXoAQeg2LITKHuurqAbiLoXYnReWaKKGWQ3vUKQiUzzwThDB0ITGEs5bEr6XKZR7AzDKroN9GgRcjZ+ge5WfKZ2RuOlkNKpr9ZN4tiq9qB6DPgIqEgfKFTsRkcg4RgmUTeHGCASYH5PVaVjkakZm2Pm9jDIia66DSFQMj5cnLywlkyeOoWRqU22yO2o0zVf23nM8pADQhGBA+EOaY2/MdVOK81l9gqsPGDD80FfzCbbe39D5PZgprvaXFp9U2d2MUbuJf58qhJvTzE0k8h7YbJcv4mpJD3l7MW+tV0Xf/mb9NqwjOIniO8XaHHJtDdF3Gi9NnkYzJl7uLvxP2CEha6mU+S1NQAEgWtMCeohfY1zzmb34OyY3ysn/LncVe3pqPdto6hFDSA0wnNeqOpmgy/EnUmh3O23VxoKlDWKOmPh4CKtbwkzHBxo8ryHfO01K6uCdrInGuF5te5jeeo2COVWMiXzK0/5pv+0HmbCs="

cache:
  directories:
    - vendor

install:
  - make deps

script:
  - "./script/ci-build"

deploy:
  skip_cleanup: true
  provider: script
  script: "./script/ci-deploy"
  on:
    branch: master
