language: go

go:
  - '1.17'

services:
  - docker

env:
  global:
    - REPO=quay.io/wantedly/k8nskel
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e 's/[^a-zA-Z0-9]/_/g')
    - TAG=$BRANCH-${TRAVIS_COMMIT::8}
    - secure: "bCT+Rmv8HcQ80Cn0XknpZftMqxSzGrEGCv0rSz5aVg4RPs6Jlh/mSp3FMzu5RseTvSXoS5hXlnqQZQwnv52eWRPaa1LaX0GIDSoFNh6ZuXLkYuskQI//pk2+vt0I4S8MNQ4nauwmo1OEBQzEueG7Tn9B/0k7oG811L/8OHwUgqU0bLN6zseEf0AqKclQUf5zOZN9LYDFTIsK75r3YzpiNmOhc763imdIzcLWhq1etqatIoiPqOIAb18AiJ/NTx0tdiWI9xtl6BG/zeHIt4jwYX5wdMsQs9xMSAjC78gI205094NwPvSUHiw4mvdnChrc2mVs9y/PkCeWx5C0fi2EkdNvgblKvHjw+BbxAVXjUHrHpIqI+FeO1exWkD1AWvpYCfsRjWj1xb0FSJ1ADWTand/dd8ce5aQUc+jjpZy1GU3mINZJ9vSmXR76DMl7KU0VLmD/u7RVBYLxDSoZtaQmNZhWAZ2RTba5OzQ+0srVBZ4cimGmweGMw3LLeQIoXC+IGHI837SR7oCA3s4jDhEKAehZIk924QPK3QWEreMIP9ij94Atxxdbv7vq5QU68I/35ndT+y76W8W6heisorPrDwOObmiD40L7LbztR5uDr6CR227nK3Rng6f/Frty3eVQYPHEi69vmhwXWqXPy7oyDkoakrmH48N9AN9fdD0s0KA=" # DOCKER_USERNAME
    - secure: "SB4gW1BRAQyknqU0HNVkk3qvs2paIFJ2tAgvtBJQZ9gtCGlwDCN9xmSv0zfDg9NIS5Ayzx4S4cMGX1Hfux9DdQB1yytG0vd/z1xifYEMIvIyjvu+0MgtDSUbrqaRzIP2aeQ71i/s13Kfn+U9Lq8ul1ObT1/ZpzXu7bHLzjr+p9FKOT/Lcl+RDzRg8RMTgH4dCLfsl15pR2XLaQoCTmqEi1sR0GObQIUIk7Q4Vv18LzQaXJz4BCi7w1UNh2P9wOKDuWHCtf+nPmOdgryXs82LmFZaACJL1cpoiYZpkujr0HOuM9gxL3Xc9E+uwmB6o/3+op3xIH0wUoDWGitIQnviUo3PXPPNYa9Et2zAxxMF9Fzj9AcrFW711K+lmwAHufGTtx3Jt2RpneScVG0zKbvGmMjjHmqodRIjwZ3C53dvIJE4z1Rs4ad0NggavIAdXgKo/KgcWsxKVDcHFrzYgWbOHJa2Ut4xUNhZ9ASQqFRnGEcYvlPkzfSnParlra842EvFukVPjA/FLx8+/5DG1U4qY1nuv4kWFOzXMeWRne+hoX0lFK3meGs/RBydsB/4SYyxHFbRw4pCxaagZHwM3NWlU2KQbhZ/EakULXGIyPAOuywp8HLIXjwV1noP7FP2gsv8x7KJawckufw8YOrgubfnbB943TZWwy4rzk8idoKRkiQ=" # DOCKER_PASSWORD

cache:
  directories:
  - $GOPATH/pkg/mod

install:
  - make deps

script:
  - "./script/ci-build"

deploy:
  skip_cleanup: true
  provider: script
  script: "./script/ci-deploy"
  on:
    branch: master
