#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

echo "docker login"
docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io

echo "docker tag ${REPO}:${TAG} ${REPO}:latest"
docker tag $REPO:$TAG $REPO:latest

echo "docker push ${REPO}:latest"
docker push $REPO:latest
